// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV3eEptZxYyb5pdch_Qb6mHgyzggHfVxk',
    appId: '1:629302967205:web:c49d41dd460822a619464c',
    messagingSenderId: '629302967205',
    projectId: 'mylibrary-flutter',
    authDomain: 'mylibrary-flutter.firebaseapp.com',
    storageBucket: 'mylibrary-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQE2dG-snW6J8uPVNRtyBfAAHdaDfW9w',
    appId: '1:629302967205:android:946bbf614dd1b38119464c',
    messagingSenderId: '629302967205',
    projectId: 'mylibrary-flutter',
    storageBucket: 'mylibrary-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV3eEptZxYyb5pdch_Qb6mHgyzggHfVxk',
    appId: '1:629302967205:web:8a787360c56c8d3919464c',
    messagingSenderId: '629302967205',
    projectId: 'mylibrary-flutter',
    authDomain: 'mylibrary-flutter.firebaseapp.com',
    storageBucket: 'mylibrary-flutter.firebasestorage.app',
  );
}
